extends: ['eslint:recommended', 'plugin:react/recommended']
env:
  es6: true
  browser: true
  serviceworker: true
  jest: true

parser: "@babel/eslint-parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
  - react

rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
  no-useless-escape: 0
  react/display-name: 0
  react/react-in-jsx-scope: 0
